### ISSUE TITLE
Websocat client cannot connect even though wscat does?

### ISSUE THREAD

**Issue by Aracki** [vi/websocat#244]
`wscat -c ws://node-ethereum:8545` does connect, but `websocat ws://node-ethereum:8545` just timeout with 

```
websocat: WebSocketError: I/O failure
```

How can I debug this type of error? (version `websocat 1.13.0`)

**Comment by vi** [comment]
Try capturing a traffic dump. Alternatively, make Websocat log traffic itself.

    websocat -t - ws-c:log:tcp:node-ethereum:8545

Of of reasons NodeJS-based tool can connect while other tools can't is the lack of [permessage-deflate](https://datatracker.ietf.org/doc/html/rfc7692) support and forced, unconditional usage of it by server.

Using `strace` or analogue can also be helpful.

---

> I/O failure

What if you try to use explicit IP address instead of `node-ethereum`?

**Comment by Aracki** [comment]
The problem was that `websocat` doesn't print that it's connected and some of the messages I was sending caused it to return I/O failure 🤦 

Sorry, it was working from the beginning. It's just that a find "connected" output more convenient to know if you can start sending messages over websocket like `wscat` does with `-c` flag.
